# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 381)
        MainWindow.setFixedSize(641,381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 461, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.connected_clients = QtWidgets.QListWidget(self.centralwidget)
        self.connected_clients.setGeometry(QtCore.QRect(480, 30, 151, 251))
        self.connected_clients.setWordWrap(False)
        self.connected_clients.setItemAlignment(QtCore.Qt.AlignLeading)
        self.connected_clients.setObjectName("connected_clients")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 290, 411, 51))
        self.textEdit.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.textEdit.setObjectName("textEdit")
        self.disconnect_button = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect_button.setGeometry(QtCore.QRect(520, 300, 111, 31))
        self.disconnect_button.setStyleSheet("background-color: rgb(226, 0, 0);\n"
"color: white;")
        self.disconnect_button.setObjectName("disconnect_button")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(430, 300, 81, 31))
        self.send_button.setAutoFillBackground(False)
        self.send_button.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"color: white;\n"
"")
        self.send_button.setDefault(False)
        self.send_button.setFlat(False)
        self.send_button.setObjectName("send_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 10, 41, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.connected_clients.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.disconnect_button.setText(_translate("MainWindow", "DISCONNECT"))
        self.send_button.setText(_translate("MainWindow", "SEND"))
        self.label.setText(_translate("MainWindow", "USERS: "))